name: rlmpc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.10.0
  - cudatoolkit=11.3
  - numpy=1.20.0
  - pyyaml>=5.3.1
  - scipy>=1.5.0
  - tensorboard>=2.2.1
  - pybind11 # conda install -c conda-forge pybind11
  - scipy # conda install scipy
  - pip:
    - inputs == 0.5
    - hydra-core == 1.1.0
    - omegaconf == 2.1
